name: Build & Deploy NestJS with MySQL

on:
  push:
    branches:
      - develop-v7

jobs:
  build-deploy:
    name: Build and Deploy NestJS with MySQL
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: devoteam_resources_hub
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install MySQL Client & Create Test DB
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-client
          mysql -h 127.0.0.1 -u root -e "CREATE DATABASE IF NOT EXISTS test_devoteam_resources_hub;"

      - name: Create .env file for CI
        run: |
          echo "DATABASE_HOST=localhost" >> .env
          echo "DATABASE_PORT=3306" >> .env
          echo "DATABASE_USER=root" >> .env
          echo "DATABASE_PASSWORD=" >> .env
          echo "DATABASE_NAME=test_devoteam_resources_hub" >> .env

      - name: Install Dependencies
        run: npm install

      - name: Debug Directory
        run: ls -la src/auth

      # - name: Run Unit Tests
      #   run: npm test

      - name: Build the Application
        run: npm run build

      - name: Get Timestamp
        id: date
        run: echo "timestamp=$(date +'%Y-%m-%d%H-%M-%S')" >> $GITHUB_ENV

      - name: Convert Docker Hub Username to Lowercase
        id: lowercase_username
        run: echo "DOCKER_USERNAME=$(echo ${{ secrets.DOCKER_HUB_USERNAME }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Build Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: false
          tags: ${{ env.DOCKER_USERNAME }}/nestjs-mysql:${{ env.timestamp }}

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push to DockerHub
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ env.DOCKER_USERNAME }}/nestjs-mysql:${{ env.timestamp }}


          